spring.application.name=job.data.rest


spring.datasource.url=jdbc:postgresql://localhost:5432/job
spring.datasource.username=postgres
spring.datasource.password=Sudhan@123
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=8081